### PR TITLE
 Css-Floating-And-Layout-PR

### PR DESCRIPTION
**Pull request by Gabkings**
# The New York Times Page

> This is a frontend project with the main aim of learning how to make html5 forms by cloning the Intuit Signup page.
###  Header Section

- It has a login and subscribes button
- Logo
- Search icon and a title
- Header Banner Image with Heading and description

###  Article Sections

- It has a title
- Date published and media icons for sharing content.
- Main body 
- A video and an image

### The Inflation section
- It has a title
- Descriptions
- Illustrations diagrams with simple explanations below each diagram.

### Related articles 
- It has a title
- Descriptions
- Image of the article
- Date when published 
- The sidebar of the latest

### Website Footer
 - Copy right 
 - Policies Links
- Links to the main sections of the website.

### Screenshorts

footerpart
related1
related2
theory

## Built With

- HTML5,
- CSS3

## Live Demo

[Live Demo Link](https://rawcdn.githack.com/SigmaSam/PositioningandFloatingElementsGabriel-Samuel/9b15f1bbf4cf0bf422fe5269db33f025e7422963/index.html)

## Getting Started

**This is an example of how you may give instructions on setting up your project locally.**
**Modify this file to match your project, remove sections that don't apply. For example: delete the testing section if the current project doesn't require testing.**

To get a local copy up and running follow these simple example steps.

### Prerequisites
- HTML5 semantic tags
- CSS3 
- Git Workflow

### Setup
- Clone the repo: ```https://github.com/SigmaSam/PositioningandFloatingElementsGabriel-Samuel.git```

### Install
- Open index.htnl with the browser of your choice

## Authors
👤 **Author1**

- Github: [@githubhandle](https://github.com/Gabkings)

- Linkedin: [linkedin](https://www.linkedin.com/in/gabriel-gitonga-b5a611183/)

👤 **Author1**

- Github: [@githubhandle](https://github.com/SigmaSam)

## 🤝 Contributing

Contributions, issues, and feature requests are welcome!

Feel free to check the [issues page](issues/).

## Show your support

Give a ⭐️ if you like this project!

## Acknowledgments

- Hat tip to anyone who's code was used
- Inspiration
- etc

## 📝 License

This project is [MIT](lic.url) licensed.

### CODE REVIEW

**Comment by mikenath223** [comment]
### Pull request currently under review by Michgolden Ukeje (TSE).
Kindly exercise patience 👋

**Review by mikenath223 — CHANGES_REQUESTED** [review]
### Hi Team 👋

You've done quite well on this project. Your pull request message is well written and descriptive enough. This is commendable.👏

However, there are test a few changes to be made to get your project looking even more awesome:
- [ ] Required - The image description just below the top header image is overflowing its container. Kindly fix this overflow issue.
**THIS IS YOURS**👇
ice_screenshot_20200422-002921

**THIS IS WHAT IS EXPECTED**👇
ice_screenshot_20200422-002934

- [ ] Required - Also please add an `Editors Picks` sidebar that can be seen at the right section of the page.[Screenshot]👇
ice_screenshot_20200422-003003

- [ ] Required - In addition kindly add more margin between the group of small images and their respective articles, seen at the mid-level of the page. Also, add the author section to the bottom of the section, as it doesn't appear in yours. The areas to correct are circled in red. [Screenshot]👇
Inkedice_screenshot_20200422-003030_LI

- [ ] Optional - Also consider fixing the scrollbar issue the appears at the bottom of the page.

Kindly fix these issues and request another review👍

**Once more, your Pull request message looks awesome.**👏

Feel free to contact me on slack(michgolden) if you need further clarification.

HAPPY CODING👨‍💻

**Comment by SigmaSam** [comment]
-Fixed the issues referred to in the last review.
-Added README.md file.

**Comment by addod19** [comment]
## Pull Request under review by Daniel Larbi Addo (TSE)

**Review by addod19 — CHANGES_REQUESTED** [review]
## Status: Require changes ♻️ 🚥 

Hi @Gabkings  and @SigmaSam  you did a great job with this project 👍 congrats 😄 However, to improve our project and make it even better, let us address the following comments:
-  The text is out of place, kindly check image to get a clear picture
jb
- Let us increase the space between the ```editors pick``` and the ```main content```
jb1
- The footer should also have the property as the nav (fixed position), kindly implement it
- The images overlapping with the text, let is fix it
jb2
- Kindly implement the DRY rule, ie do not repeat code in our css file
- Lett us fix the gap between the more in space and the main content
jb3
- Kindly fix the warning returned by the w3validator

Kindly make these changes and submit another code review 😄 
_Happy coding_ 👨‍💻 
Daniel Larbi Addo on slack

**Review by christianotieno — APPROVED** [review]
# PROJECT APPROVED :champagne:
Excellent job on this project guys. :fireworks:  Keep it up.
##
### The [clone](https://rawcdn.githack.com/SigmaSam/PositioningandFloatingElementsGabriel-Samuel/d2c2355b2c16533e02f538d9bdb00cd33388ff34/index.html) shows good understanding and usage of the positioning and floating of elements. :100:
##
- The cloned page is rendering as it should and meets all the project specifications.
-  The project has a descriptive README and is professionally done. Good job with that.
- Pull Request has a meaningful title and a very awesome and detailed description.
- CSS is clean. No linter errors at this point and no bad practices used as well.
- The markup as well has no errors nor warnings to show. Good job with that.
- The repo has followed all the guidelines there are to follow (GitHub flow etc.)
**All the required tasks have been fulfilled in this project. I will go ahead and mark this as complete.**
- Congratulations on the splendid job @SigmaSam  & @Gabkings! :+1:
- You can now merge to master and I wish you all the very best in your next tasks :first_place_medal:
##
Happy coding :smile:
**[Christian Otieno](https://github.com/ChristianOtieno)**
[Twitter](https://twitter.com/iamchrisotieno) [linkedin](https://www.linkedin.com/in/christianotieno/) [GitLab](https://gitlab.com/christianotieno)

**Pull request merged**
